name: Pipeline Demo

on:
  push:
    branches:
      - main

jobs:
  deploy-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Take code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@65.2.34.207 << 'EOF'
          set -e  # Exit on any command failure
          
          if [ -d "/home/ubuntu/democicd" ]; then
          echo "moving in project"
          else
          cd /home/ubuntu
          git clone https://github.com/Mayank0851/democicd
          cd democicd
          fi

      

          # Start Uvicorn in the background, redirect logs, and detach process
          #nohup env/bin/uvicorn main:app --host 0.0.0.0 --port 8080 > uvicorn.log 2>&1 & disown

          EOF
