name: Pipeline Demo

on:
  push:
    branches:
      - main

jobs:
  deploy-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Take code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@65.2.34.207 << 'EOF'
          set -e  # Exit on any command failure
          
          if [ -d "/home/ubuntu/democicd" ]; then
          echo "moving in project"
          else
          cd /home/ubuntu
          git clone https://github.com/Mayank0851/democicd
          cd democicd
          fi

          # Install Python if not already installed
          echo "Installing Python and dependencies..."
          sudo apt update && sudo apt install -y python3 python3-venv python3-pip

          # Set up virtual environment
          if [ ! -d "env" ]; then
            python3 -m venv env
          fi
          source env/bin/activate

          # Install dependencies
          pip install --upgrade pip
          pip install fastapi uvicorn -r requirements.txt  # Ensure all dependencies are installed

          # Kill any existing Uvicorn process
          pkill uvicorn || true

          # Start Uvicorn in the background
          nohup env/bin/uvicorn main:app --host 0.0.0.0 --port 8080 > uvicorn.log 2>&1 & disown

          EOF
      
