name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pip install pytest httpx
          pytest .

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t mayankvishwakarma08/fastapi-app:latest .

      - name: Push Docker Image (Public)
        run: |
          docker push mayankvishwakarma08/fastapi-app:latest

  deploy-stage:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.201.55.132 << 'EOF'
          set -e  # Exit on any command failure

          echo "Stopping and removing existing container..."
          docker stop fastapi-app || true
          docker rm fastapi-app || true

          echo "Pulling latest Docker image..."
          docker pull mayankvishwakarma08/fastapi-app:latest

          echo "Starting new container..."
          docker run -d --name fastapi-app -p 8080:8000 --restart always mayankvishwakarma08/fastapi-app:latest

          EOF

